- name: Install samba package
  ansible.builtin.apt: name=samba state=present

- name: Backup smb.conf file
  ansible.builtin.copy: 
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak
    force: false        # file will only be transferred if the destination does not exist
    remote_src: true    # src file is on the managed node

- name: Copy local config file to samba server
  ansible.builtin.copy: 
    src: smb.conf 
    dest: /etc/samba/smb.conf
    force: true         # file will be replaced when contents are different than the source
    remote_src: false   # src file is on the controller node
  register: conf_file

- name: Restart samba service if config has changed
  ansible.builtin.service: name=smbd state=restarted
  when: conf_file.changed

- name: Enable samba to start on reboot
  ansible.builtin.service: name=smbd enabled=true