---
- name: Install ufw package
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Turn off IPv6 and backup config
  ansible.builtin.lineinfile:
    backup: true
    line: IPV6=no
    path: /etc/default/ufw
    regexp: 'IPV6='
    state: present
  notify: Restart UFW service

- name: Reject all traffic and allow SSH
  community.general.ufw:
    default: reject
    state: enabled
    rule: allow
    name: OpenSSH

- name: Allow specified app if app var is defined
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
  # if app_list is undefined, enable OpenSSH again
  loop: "{{ app_list | default([OpenSSH]) }}"
