- name: Install samba package
  ansible.builtin.apt:
    name: samba
    state: present

- name: Backup smb.conf file
  ansible.builtin.copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak
    force: false        # file will only be transferred if the destination does not exist
    mode: '0644'
    remote_src: true    # src file is on the managed node

- name: Copy local config template to samba server
  ansible.builtin.template:
    src: smb.j2
    dest: /etc/samba/smb.conf
    force: true         # file will be replaced when contents are different than the source
    mode: '0644'
    remote_src: false   # src file is on the controller node
  notify: Restart samba service

- name: Enable samba to start on reboot
  ansible.builtin.service:
    name: smbd
    enabled: true
