---
- name: Configure Raspberry Pi file server
  become: true
  hosts: fileserver
  gather_facts: false
  roles:
    - mount_usb
    - configure_vsftpd
    - create_users
    - create_ftp_directories
    - configure_samba

    - role: create_ufw_app_profile
      vars:
        app: vsftpd
    - role: create_ufw_app_profile
      vars:
        app: vnc01

    - role: configure_ufw
