---
- name: Configure Plex Media Server on Raspberry Pi
  become: true
  hosts: plex
  gather_facts: false
  roles:
    - install_plex

    - role: create_ufw_app_profile
      vars:
        app: plex

    - role: configure_ufw
      vars:
        app_list:
          - plex
