---
- name: Mount USB drive
  become: true
  hosts: all
  gather_facts: false
  vars:
    disk_name: sammy500
    device: /dev/sda1

  tasks:

    - name: Display disk mount location
      ansible.builtin.debug:
        msg: "Disk will be mounted at /media/{{ ansible_user }}/{{ disk_name }}"

    - name: Mount the disk
      ansible.posix.mount:
        fstype: ext4
        opts: defaults,nofail
        passno: 0
        path: "/media/{{ ansible_user }}/{{ disk_name }}"
        src: "{{ device }}"
        state: mounted
