---
- name: Install and configure FTP
  become: true
  hosts: all
  gather_facts: false
  roles:
    - configure_vsftpd
    - create_users
    - create_ftp_directories
    - role: create_ufw_app_profile
      vars:
        app: vsftpd
    - role: create_ufw_app_profile
      vars:
        app: vnc01
    - role: configure_ufw
      vars:
        app: vsftpd
    - role: configure_ufw
      vars:
        app: vnc01
