- name: Create parent directory at {{ ftp_path | dirname }}
  ansible.builtin.file:
    group: root
    owner: root
    mode: '0755'
    path: "{{ ftp_path | dirname }}"
    state: directory

- name: Create child directory {{ ftp_path }}
  ansible.builtin.file:
    group: ftp
    owner: ftp
    mode: '0777'
    path: "{{ ftp_path }}"
    state: directory
