- name: Generate a random salt
  set_fact:
    random_salt: "{{ lookup('password', '/dev/null chars=ascii_lowercase,ascii_uppercase,digits length=16') }}"

- name: Create specified users
  ansible.builtin.user:
    create_home: true
    move_home: true
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512', random_salt) }}"
    state: present
    # update_password: always   # will update passwords if they differ
    update_password: on_create
  loop: "{{ user_list }}"
  loop_control: 
    label: "{{ item.name }}"
